#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Spine 清单生成器：扫描 assets/Spines/*.json，生成 scripts/spine_list.lua
供 Spine 编辑器左侧列表选择不同骨架预览。

用法：python3 asset_tools/gen_spine_list.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPINES_DIR = os.path.join(ROOT, "assets", "Spines")
OUT = os.path.join(ROOT, "scripts", "spine_list.lua")


def main():
    items = []
    for fn in sorted(os.listdir(SPINES_DIR)):
        if not fn.endswith(".json") or fn.endswith(".meta"):
            continue
        path = os.path.join(SPINES_DIR, fn)
        name = os.path.splitext(fn)[0]
        # 读动画名（便于列表预览，运行时也会用 GetAnimationNames 再确认）
        anims = []
        try:
            with open(path, encoding="utf-8") as f:
                d = json.load(f)
            anims = list(d.get("animations", {}).keys())
        except Exception:
            pass
        items.append((name, "Spines/" + fn, anims))

    lines = ["-- AUTO-GENERATED by gen_spine_list.py — Spine 骨架清单（编辑器左侧列表用）",
             "return {"]
    for name, src, anims in items:
        anim_str = ", ".join('"%s"' % a for a in anims)
        lines.append('  { name = "%s", src = "%s", anims = { %s } },' % (name, src, anim_str))
    lines.append("}")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print("已生成", OUT)
    for name, src, anims in items:
        print("  %-14s %s  anims=%s" % (name, src, anims))


if __name__ == "__main__":
    main()
