-- AUTO-GENERATED by gen_char_icon_spine.py — 角色图标 Spine 组件元数据
-- 图层顺序(自底向上): guangyi, body, fasi, fawei, sidai
return {
  W=606, H=634, atlasW=3030, atlasH=634, atlasImage="char_icon.png",
  src="Spines/char_icon.json",
  animDur=18.00,
  bounds={x=0, y=0, w=606, h=634},
  parts={
    {name="guangyi", disp="三菱形光翼", kind="spin", bx=252.0, by=316.0, Vx=51.0, Vy=1.0, w=606, h=634, amp=0, period=0, phase=0, spinPeriod=18.00, offX=13.0, offY=-20.0, scale=0.950, flipX=false, alpha=1.000,},
    {name="body", disp="图案本体", kind="static", bx=303.0, by=317.0, Vx=0.0, Vy=0.0, w=606, h=634, amp=0, period=0, phase=0, spinPeriod=0, offX=0.0, offY=0.0, scale=1.000, flipX=false, alpha=1.000,},
    {name="fasi", disp="发丝", kind="sway", bx=168.0, by=456.0, Vx=135.0, Vy=-139.0, w=606, h=634, amp=6.0, period=3.60, phase=0.450, spinPeriod=0, offX=0.0, offY=0.0, scale=1.000, flipX=false, alpha=1.000,},
    {name="fawei", disp="发尾", kind="sway", bx=446.0, by=185.0, Vx=-143.0, Vy=132.0, w=606, h=634, amp=3.5, period=3.60, phase=4.400, spinPeriod=0, offX=0.0, offY=0.0, scale=1.000, flipX=false, alpha=1.000,},
    {name="sidai", disp="丝带", kind="sway", bx=427.0, by=257.0, Vx=-124.0, Vy=60.0, w=606, h=634, amp=4.0, period=2.25, phase=0.000, spinPeriod=0, offX=0.0, offY=0.0, scale=1.000, flipX=false, alpha=1.000,},
  },
}
