-- AUTO-GENERATED by gen_spine_list.py — Spine 骨架清单（编辑器左侧列表用）
return {
  { name = "char_icon", src = "Spines/char_icon.json", anims = { "idle" } },
  { name = "char_idle", src = "Spines/char_idle.json", anims = { "idle" } },
  { name = "char_parts", src = "Spines/char_parts.json", anims = { "idle" } },
  { name = "staff_parts", src = "Spines/staff_parts.json", anims = { "deploy", "open", "loop", "close" } },
}
